name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php-version }} Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, json, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies via Packagist
        run: |
          # Melonggarkan strict check di level CI agar platform silang tidak memicu exit code 2
          composer validate
          composer install --prefer-dist --no-progress --ignore-platform-reqs

      - name: Validate CLI Executable
        run: php bin/db-stressmit --help